### ISSUE TITLE
Several pull requests

### ISSUE THREAD

**Issue by peterb154** [andyt530/az2tf#12]
FYI, I am just wrapping up a project where we imported LOTs of Azure resources using az2tf. Again, GREAT work and thanks! I had to make several adjustments to ensure that a `terraform plan` did not trigger a change. Also found that when importing one resource group at a time, it is helpful to have the resource group suffixed to output dir.  Submitted 8 pull requests. Feel free to include or disregard them as you see fit.

0. az2tf.sh
  added resourcegroup suffix to output

1. scripts/azurerm_express_route_circuit_peering.sh
  add peering config fi peering_type is MicrosoftPeering or AzurePrivatePeering

2. scripts/azurerm_lb_probe.sh
  remove double quotes (") from requestPath string

3. scripts/azurerm_log_analytics_workspace.sh
  If rdays == 7 (which is an invalid value), dont add to rention_days .tf file. Valid valise must be between 30 and 120

4. scripts/azurerm_management_lock.sh
  If lock notes are null, dont add to tf file. 

5. scripts/azurerm_storage_account.sh
  skip creating bypass rules with the Only bypass network is "AzureServices" and there are no "ipRules" or "virtualNetworkRules" defined

6. scripts/azurerm_virtual_network_gateway_connection.sh
  authorization_key should only be added to tf file when not null

7. README.md
  Added warning about Virtual Network Gateway always signaling change

**Comment by andyt530** [comment]
All merged in - thank you !
