### ISSUE TITLE
Parsing port range with "-" causes scripts to fail

### ISSUE THREAD

**Issue by jarens7** [andyt530/az2tf#14]
When parsing "security_rule" and a port range such as 65503-65534 is encountered, the import fails with the following error: 

 Error loading the state: Error loading backend config: Error parsing 
 /terraform/az2tf/tf.*****************/azurerm_network_security_group.***********__*******.tf: At 40:32: 
 literal not terminated

 Please ensure that your Terraform state exists and that you've
 configured it properly. You can use the "-state" flag to point
 Terraform at another state file

Referencing the output shows the following:
`
	 security_rule { 
		 name = "some_name"  
                           description = "some_description"  
		 access = "Allow"  
		 priority = "103"  
		 protocol = "Tcp"  
		 direction = "Inbound"  
		 source_port_range = "*"  
		 source_address_prefix = "*"  
		 destination_port_range = "65503-65534  
		 destination_port_range = "  
		 destination_address_prefix = "*"  
`

Judging by this output and having verified the rule is correct in the web console it appears the "-" is breaking the parsing as the "destination_port_range" appears twice but in a broken method.

**Comment by andyt530** [comment]
Hi - Pretty sure I've fixed this one - let me know if you have more problems

**Comment by jarens7** [comment]
Awesome work thank you!
