### ISSUE TITLE
application_gateway capacity null

### ISSUE THREAD

**Issue by xarly** [andyt530/az2tf#15]
I'm getting

`Error: azurerm_application_gateway.MyResourceGroup__myAppGw: sku.0.capacity: cannot parse '' as int: strconv.ParseInt: parsing "null": invalid syntax`

`Terraform v0.11.10
└── provider.azurerm >= 1.19.0`

Thanks

**Comment by andyt530** [comment]
committed a workaround - let me know what output you get with regards this gateway now
