### ISSUE TITLE
Resources 0 of 0

### ISSUE THREAD

**Issue by KevinDMack** [andyt530/az2tf#16]
I'm new to this tool, but when I cloned the repo, I made sure all dependencies were installed and up to date using an Ubuntu Linux subsystem on windows 10 and executing from vs code.  The az2tf runs for the appropriate subscription and resource group, identifying that it has found both, but continually comes up with no resources.  So the output I get contains an empty azurerm_resource_group__{resource group name}.tf that only has the resource group TF implementation.  

When I check the TF State, it also shows only the resource group with no other resources.  I thought this might be a permissions issue but I am an owner on the subscription and am able to run the commands from the various SH files and get back results.  

One other point is that I am trying to execute this against Azure Government, and made sure that my Azure CLI context is logged in to Azure Government first.  Like I said it still finds the appropriate subscription and resource group, but is failing to find any of the resources in that resource group.

**Comment by andyt530** [comment]
I doubt this tool will work on Azure Government - that has some differences compared to public Cloud.
I have no access to a Government Cloud setup to test it.

Early on in the process az2tf calls out to resources.azure.com to get a list of things it needs to do - I doubt Azure Government resources appear there, so it is going to run into trouble early on.

I have also never tested this tool on the Linux subsystem - it aught to work in theory.

**Comment by KevinDMack** [comment]
Actually once I made that one change on the resource.sh at line 9 the whole thing works.  The key is that prior to running az login, you set the cloud to azure gov, and after that it all works. And works to republish as well.  If we could pass a parameter to denote cloud we could plug in the updated url.  The azure government developers guide actually has all the url mappings.
