### ISSUE TITLE
No dots allowed in resource group or resource names. Throws errors in Terraform!?

### ISSUE THREAD

**Issue by jomeier** [andyt530/az2tf#17]
Hi,

today I got an error during scanning of my subscription with az2tf.

I have a resource group with dots in its name like 'dns-zone-apps-q.hello.com'.

```
dns-zone-apps-q.hello.com
resource "azurerm_resource_group" "dns-zone-apps-q.hello.com" {
         name = "dns-zone-apps-q.hello.com"
         location = "westeurope"
}
Error removing items from the state: Error parsing address 'azurerm_resource_group.dns-zone-apps-q.hello.com': invalid resource address "azurerm_resource_group.dns-zone-apps-q.hello.com"

The state was not saved. No items were removed from the persisted
state. No backup was created since no modification occurred. Please
resolve the issue above and try again.
Error: invalid resource address "azurerm_resource_group.dns-zone-apps-q.hello.com"

For information on valid syntax, see:
https://www.terraform.io/docs/internals/resource-addressing.html

Error: invalid resource address "azurerm_resource_group.dns-zone-apps-q.hello.com"
Error in log file exiting ....
```

Maybe it's a good idea to translate all names from Azure to something which is ok for terraform before writing it out to tf files?

Best regards,

Josef

**Comment by andyt530** [comment]
posted a fix for this

**Comment by jomeier** [comment]
Hi Andy,

thank you. But I fear that's not enough because each resource (public ip addresses, ...) gets a reference to the resource group with the dots in it's name. The rg must also be patched there :-(

Best regards,

Josef

**Comment by andyt530** [comment]
I can fix that - working on it ....

**Comment by andyt530** [comment]
committed a bunch of fixes for this.  It's not perfect "." is/are replaced with "-"  in terraform resource names. So "rg.a.b"  gets renamed to "rg-a-b". But if you happened to have both to start with - there will be a clash.

**Comment by jomeier** [comment]
Thank you !
