### ISSUE TITLE
Can't find subscription?

### ISSUE THREAD

**Issue by nexxai** [andyt530/az2tf#18]
Ok so I'm almost 100% sure this is a user problem and not a problem with the code, but at this point I feel a bit lost and hope someone can point me in the right direction.

Given the following subscription (displayed after I login via "az login"):
```
[
  {
    "cloudName": "AzureCloud",
    "id": "a86bc126-XXXX-XXXX-XXXX-7e546be7a509",
    "isDefault": false,
    "name": "SW.IT.BI.XXXXXXXXXXX.PRD",
    "state": "Enabled",
    "tenantId": "b9cdd4bf-XXXX-XXXX-XXXX-2f0cfec740cf",
    "user": {
      "name": "admin.XXXXXXXXX@XXXXXXXXX.com",
      "type": "user"
    }
  }
]
```

I've tried using both the name of the subscription (e.g. "SW.IT.BI.XXXXXXXXXXX.PRD") and the id (e.g. "a86bc126-XXXX-XXXX-XXXX-7e546be7a509") but I get the following errors:

```
➜  az2tf git:(master) ./az2tf.sh -s SW.IT.BI.XXXXXXXXXXX.PRD   
Checking Subscription SW.IT.BI.XXXXXXXXXXX.PRD exists ...
parse error: Invalid numeric literal at line 2, column 4
Could not find subscription with ID SW.IT.BI.XXXXXXXXXXX.PRD
➜  az2tf git:(master) ./az2tf.sh -s a86bc126-XXXX-XXXX-XXXX-7e546be7a509
Checking Subscription a86bc126-XXXX-XXXX-XXXX-7e546be7a509 exists ...
parse error: Invalid numeric literal at line 2, column 4
Could not find subscription with ID a86bc126-XXXX-XXXX-XXXX-7e546be7a509
```
I definitely have permissions to that subscription so I don't think it's a permissions issue, but I'm not really sure where else to look.

**Comment by andyt530** [comment]
the -s is expecting a subscription id - you can't use a subscription name

the az2th.sh - runs this command to get a list of subscriptions: 

az account list --query '[].id' | jq '.[]' | tr -d '"'

Try running this command above - it should return a list of subscription id's

one of which should be a86bc126-XXXX-XXXX-XXXX-7e546be7a509

Is this so ?

**Comment by nexxai** [comment]
Wow, thanks for getting back to me so quickly!
```
➜  az2tf git:(master) az account list --query '[].id' | jq '.[]' | tr -d '"'
parse error: Invalid numeric literal at line 2, column 4
```
However if I do: 
```
➜  az2tf git:(master) az account list --query '[].id' 
[
  "10963f71-XXXX-XXXX-XXXX-76109759447c",
  "464daa41-XXXX-XXXX-XXXX-5bb3ab855efb",
  "a86bc126-XXXX-XXXX-XXXX-7e546be7a509"
]
```
and then 
```
➜  az2tf git:(master) az account list --query '[].id' | jq '.[]'
parse error: Invalid numeric literal at line 2, column 4
```
So it would seem that something is up with jq not parsing the list correctly?

I'm running the latest version:
```
➜  az2tf git:(master) jq --version
jq-1.6
```
Any ideas on what else I could check?

**Comment by andyt530** [comment]
Which Operating System are you using  ?

Upgraded to jq 1.6 on my macOS   - but it still works ok here.....

**Comment by nexxai** [comment]
macOS Mojave 10.14.2 (18C54)

**Comment by andyt530** [comment]
me too ... this is odd.  
az version ?

**Comment by nexxai** [comment]
Ok now here's something even weirder: if I copy the text and manually pipe it through echo, it works fine:
```
➜  az2tf git:(master) echo '["10963f71-XXXX-XXXX-XXXX-76109759447c","464daa41-XXXX-XXXX-XXXX-5bb3ab855efb","a86bc126-XXXX-XXXX-XXXX-7e546be7a509"]' | jq '.[]'
"10963f71-XXXX-XXXX-XXXX-76109759447c"
"464daa41-XXXX-XXXX-XXXX-5bb3ab855efb"
"a86bc126-XXXX-XXXX-XXXX-7e546be7a509"
➜  az2tf git:(master) az -v     
azure-cli (2.0.52)
```

**Comment by nexxai** [comment]
For posterity's sake, I upgraded azure-cli to 2.0.54 but am still having the same problem.  I've also opened a case on the jq GitHub repo (https://github.com/stedolan/jq/issues/1787) in case this is something they can shed some light on.

**Comment by andyt530** [comment]
we could replace the line in az2tf.sh with:

az account list --query '[].id' | cut -f2 -d '"' | grep "-"

My concern would be that your jq issues will cause other problems as this tool uses jq everywhere !

**Comment by nexxai** [comment]
So yeah that definitely allowed it to proceed past the original failure point but it wasn't able to find any resource groups, etc.  I think I'll wait to hear back from the jq team about what could be wrong.

**Comment by andyt530** [comment]
I installed jq with brew  - did you ?

**Comment by nexxai** [comment]
Yeah, and I just tried uninstalling and reinstalling it, and the same thing happened. 

¯\\\_(ツ)\_/¯

**Comment by nexxai** [comment]
Ok so I figured out the problem: for some reason azure-cli is inserting ANSI color codes in the output before it's piped to jq.  (Possibly because I'm using oh_my_zsh instead of the standard BASH shell?)

The solution is to add the option: `-o json` to each call of az like this:
```
az account list --query '[].id' -o json | jq '.[]' | tr -d '"'
```
which tells azure-cli to print to stdout without the color codes.  I've tried adding to various combinations that you've got in your script but I still haven't figured out which ones need it and which don't.  I'll keep working on it if I can find some time this week, but if you are able to check too, that would be a great help.

**Comment by andyt530** [comment]
Good find - I'll get that into all of the code this weekend ....

**Comment by nexxai** [comment]
Thank you so much!

**Comment by andyt530** [comment]
found some time - uploaded all the changes - let me know how you get on ?

**Comment by nexxai** [comment]
Oh wow, it got WAY farther this time.  It generated a bunch of .tf files (PROGRESS!) but it eventually spit out this error:
```
Terraform Plan ...

Error: Error asking for user input: Error parsing address 'azurerm_resource_group': invalid resource address "azurerm_resource_group"
```
Is that a me-problem?

**Comment by andyt530** [comment]
If you didn’t - delete the tf.xxxxx-xxxx-xxxx-xxxxxx directory before you run az2tf.sh

That error looks like there may be a malformed .tf file hanging around from a previous run

**Comment by nexxai** [comment]
So it looks like it works **beautifully** (haven't found any problems) except this error is thrown near the beginning but the whole script continues and seems to work fine otherwise?

`az lock list: error: argument --query: invalid jmespath_type value: '[].resourceGroup -o json'`

Not sure if that's important or not?

**Comment by andyt530** [comment]
typo in az2tf.sh causing that - just posted fix.  You only need to run again if you are using locks and want them terraform'ed.

**Comment by nexxai** [comment]
Love it!

I know we use Logic Apps, Function Apps, Data Lakes and Data Factories here pretty heavily so I'll work on adding them as scripts and will submit PRs in the next few weeks if you're OK with that?  I'm leaving for holidays tomorrow so I won't have much time in the next week or two, but I'll do what I can.

Thank you again for such an awesome tool!
