### ISSUE TITLE
error while running script on Mac

### ISSUE THREAD

**Issue by kantkrish** [andyt530/az2tf#19]
Unzipped the file to a new folder
Azure cli and terraform is installed

When I ran the az2tf.sh referencing my subscription ID, I am getting following error:

./az2tf.sh: line 50: jq: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

Am I missing something?

**Comment by andyt530** [comment]
You need to install jq

https://stedolan.github.io/jq/

On MAC you can also install with brew
$ brew install jq

I'll update the Readme
