### ISSUE TITLE
BuiltInRole types

### ISSUE THREAD

**Issue by peterb154** [andyt530/az2tf#2]
Hello, I love the solution that you have developed here. It is a huge help in getting control of a pre-existing Azure environment. Thanks so much for creating and maintaining this tool. 

I noticed that the tool imports all of the [86 BuiltInRole types](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles) by default. I am not an Azure expert, but I cant think of a reason why we'd want to have these role type under terraform control. In my circumstance, having them made organizing the imported tf files and state into a nice repo/workspace a little messy.

Yes, I could do something like:
```
for file in `ls rdf__*`; do
 resource=`$echo $file | sed s/'.tf'//`
 terraform state rm azurerm_role_definition.${resource}
 rm $file
done
```
But I'd have to be careful not to delete any custom roles..

So, I thought it might be easier to modify scripts/azurerm_role_definition.sh to exlcude BuiltInRole types from import. 
```
 18         type=`echo $azr | jq ".[(${i})].roleType"`
 19         if [ $type == "\"BuiltInRole\"" ]; then
 20                 continue
 21         fi
```
Let me know if you can think of any negative consequences of doing this. 
If there are some reasons to import them, perhaps we could add an option to --exclude BuiltInRole  to az2tf.sh
If you would like a pull request, let me know.

**Comment by andyt530** [comment]
HI Brian,

You are correct there is no reason.

Thanks for the code snippet - I'll try and get that in by Monday.

Thanks

Andy
________________________________

**Comment by peterb154** [comment]
Just sent a pull request. Looks like you might want to update tabs/spaces to get the indent right. 

Thanks again!

**Comment by peterb154** [comment]
Thanks!
