### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by RoAnBu** [andyt530/az2tf#25]
Hi, thank you for creating az2tf! It saves me a lot of work.

However it would be awesome if you could specify a license so that it can be safely used in commercial projects. Thanks!

**Comment by andyt530** [comment]
Hi,

Happy to add the most permissive license.
But I confess I've never done this before - any tips / links to how I do it ?

**Comment by RoAnBu** [comment]
MIT License would be great, because it allows pretty much everything. The only usage requirement is a copyright notice (see https://choosealicense.com/licenses/mit/).

The GNU General Public License v3.0 (https://choosealicense.com/licenses/gpl-3.0/) is similar but requires the user to use the same license if the project is republished (for example if I want to publish a modified version of the project on Github). Some companies don't like this license because of the "same license" clause and will try to avoid projects with GPL.

A very short and awesome overview of open source licenes can be found here: https://choosealicense.com/licenses/ 

You can add the license to the project by adding a simple LICENSE file (possibly you need to replace some placeholders in the license beforehand). For example see this project: https://github.com/adam-p/markdown-here

**Comment by andyt530** [comment]
OK - think I've added an MIT license.

**Comment by RoAnBu** [comment]
Awesome, thank you for responding so fast!
