### ISSUE TITLE
Script adds user directory to resource's ID

### ISSUE THREAD

**Issue by DanteNahuel** [andyt530/az2tf#29]
When the script is run from Windows Git Bash, the .tfstate stores the resource id for each resource with the user's directory from which the bash is run added to the id attribute 
Like this:
```

azurerm_network_interface.az-rg-tf__az-tfvm-br963

      ip_configuration.0.public_ip_address_id: "C:/Program Files/Git/subscriptions/subscriptionid/resourceGroups/az-rg-tf/providers/Microsoft.Network/publicIPAddresses/az-tfvm-br-ip"

```
     
 We have to remove it manually from all the tfstate because this causes differences with the resources when we run the terraform plan command.

**Comment by andyt530** [comment]
The terraform state file is managed entirely by terraform itself.

I'd suggest creating an issue with Hashicorp here:
https://github.com/hashicorp/terraform
